# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LandOfficeAdministrativeSettingsDialog.ui'
#
# Created: Thu Oct 08 10:59:35 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LandOfficeAdministrativeSettingsDialog(object):
    def setupUi(self, LandOfficeAdministrativeSettingsDialog):
        LandOfficeAdministrativeSettingsDialog.setObjectName(_fromUtf8("LandOfficeAdministrativeSettingsDialog"))
        LandOfficeAdministrativeSettingsDialog.resize(800, 470)
        LandOfficeAdministrativeSettingsDialog.setMinimumSize(QtCore.QSize(800, 470))
        LandOfficeAdministrativeSettingsDialog.setMaximumSize(QtCore.QSize(800, 470))
        LandOfficeAdministrativeSettingsDialog.setBaseSize(QtCore.QSize(800, 470))
        self.close_button = QtGui.QPushButton(LandOfficeAdministrativeSettingsDialog)
        self.close_button.setGeometry(QtCore.QRect(720, 430, 75, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.help_button = QtGui.QPushButton(LandOfficeAdministrativeSettingsDialog)
        self.help_button.setGeometry(QtCore.QRect(520, 430, 91, 23))
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.tabWidget = QtGui.QTabWidget(LandOfficeAdministrativeSettingsDialog)
        self.tabWidget.setGeometry(QtCore.QRect(6, 8, 786, 416))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.groupBox = QtGui.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(7, 4, 766, 341))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.land_office_name_edit = QtGui.QLineEdit(self.groupBox)
        self.land_office_name_edit.setGeometry(QtCore.QRect(10, 40, 210, 22))
        self.land_office_name_edit.setObjectName(_fromUtf8("land_office_name_edit"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 210, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(11, 70, 210, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.address_edit = QtGui.QTextEdit(self.groupBox)
        self.address_edit.setGeometry(QtCore.QRect(10, 90, 210, 110))
        self.address_edit.setObjectName(_fromUtf8("address_edit"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(12, 200, 210, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.bank_cbox = QtGui.QComboBox(self.groupBox)
        self.bank_cbox.setGeometry(QtCore.QRect(10, 220, 211, 22))
        self.bank_cbox.setObjectName(_fromUtf8("bank_cbox"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 250, 210, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.bank_account_num_edit = QtGui.QLineEdit(self.groupBox)
        self.bank_account_num_edit.setGeometry(QtCore.QRect(10, 270, 210, 22))
        self.bank_account_num_edit.setObjectName(_fromUtf8("bank_account_num_edit"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(260, 20, 210, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.phone_edit = QtGui.QLineEdit(self.groupBox)
        self.phone_edit.setGeometry(QtCore.QRect(260, 40, 210, 22))
        self.phone_edit.setObjectName(_fromUtf8("phone_edit"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(260, 70, 210, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.fax_edit = QtGui.QLineEdit(self.groupBox)
        self.fax_edit.setGeometry(QtCore.QRect(260, 90, 210, 22))
        self.fax_edit.setObjectName(_fromUtf8("fax_edit"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(260, 120, 210, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.email_address_edit = QtGui.QLineEdit(self.groupBox)
        self.email_address_edit.setGeometry(QtCore.QRect(260, 140, 210, 22))
        self.email_address_edit.setObjectName(_fromUtf8("email_address_edit"))
        self.web_site_label = QtGui.QLabel(self.groupBox)
        self.web_site_label.setGeometry(QtCore.QRect(260, 170, 210, 17))
        self.web_site_label.setObjectName(_fromUtf8("web_site_label"))
        self.web_site_edit = QtGui.QLineEdit(self.groupBox)
        self.web_site_edit.setGeometry(QtCore.QRect(260, 190, 210, 22))
        self.web_site_edit.setObjectName(_fromUtf8("web_site_edit"))
        self.tabWidget.addTab(self.widget, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(20, 15, 210, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.zone_location_cbox = QtGui.QComboBox(self.tab_2)
        self.zone_location_cbox.setGeometry(QtCore.QRect(14, 30, 216, 22))
        self.zone_location_cbox.setObjectName(_fromUtf8("zone_location_cbox"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(20, 65, 210, 13))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 70, 150, 140))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(15, 25, 130, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(15, 65, 130, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.from_zone_cbox = QtGui.QComboBox(self.groupBox_2)
        self.from_zone_cbox.setGeometry(QtCore.QRect(10, 40, 130, 22))
        self.from_zone_cbox.setObjectName(_fromUtf8("from_zone_cbox"))
        self.to_zone_cbox = QtGui.QComboBox(self.groupBox_2)
        self.to_zone_cbox.setGeometry(QtCore.QRect(10, 80, 130, 22))
        self.to_zone_cbox.setObjectName(_fromUtf8("to_zone_cbox"))
        self.copy_fees_button = QtGui.QPushButton(self.groupBox_2)
        self.copy_fees_button.setGeometry(QtCore.QRect(10, 110, 131, 23))
        self.copy_fees_button.setObjectName(_fromUtf8("copy_fees_button"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(460, 70, 310, 140))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.update_contracts_button = QtGui.QPushButton(self.groupBox_3)
        self.update_contracts_button.setGeometry(QtCore.QRect(160, 65, 140, 23))
        self.update_contracts_button.setObjectName(_fromUtf8("update_contracts_button"))
        self.update_date = QtGui.QDateEdit(self.groupBox_3)
        self.update_date.setGeometry(QtCore.QRect(19, 66, 130, 22))
        self.update_date.setKeyboardTracking(True)
        self.update_date.setCalendarPopup(True)
        self.update_date.setTimeSpec(QtCore.Qt.LocalTime)
        self.update_date.setObjectName(_fromUtf8("update_date"))
        self.zones_lwidget = QtGui.QListWidget(self.tab_2)
        self.zones_lwidget.setGeometry(QtCore.QRect(20, 80, 210, 130))
        self.zones_lwidget.setObjectName(_fromUtf8("zones_lwidget"))
        self.land_fee_twidget = QtGui.QTableWidget(self.tab_2)
        self.land_fee_twidget.setGeometry(QtCore.QRect(20, 220, 706, 161))
        self.land_fee_twidget.setMinimumSize(QtCore.QSize(441, 0))
        self.land_fee_twidget.setAutoFillBackground(True)
        self.land_fee_twidget.setObjectName(_fromUtf8("land_fee_twidget"))
        self.land_fee_twidget.setColumnCount(4)
        self.land_fee_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.land_fee_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.land_fee_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.land_fee_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.land_fee_twidget.setHorizontalHeaderItem(3, item)
        self.land_fee_twidget.horizontalHeader().setCascadingSectionResizes(True)
        self.land_fee_twidget.horizontalHeader().setDefaultSectionSize(200)
        self.land_fee_twidget.horizontalHeader().setHighlightSections(False)
        self.land_fee_twidget.horizontalHeader().setMinimumSectionSize(30)
        self.land_fee_twidget.horizontalHeader().setSortIndicatorShown(False)
        self.land_fee_twidget.horizontalHeader().setStretchLastSection(False)
        self.land_fee_twidget.verticalHeader().setCascadingSectionResizes(True)
        self.land_fee_twidget.verticalHeader().setHighlightSections(True)
        self.land_fee_twidget.verticalHeader().setMinimumSectionSize(25)
        self.land_fee_twidget.verticalHeader().setSortIndicatorShown(False)
        self.land_fee_twidget.verticalHeader().setStretchLastSection(False)
        self.add_fee_button = QtGui.QPushButton(self.tab_2)
        self.add_fee_button.setGeometry(QtCore.QRect(740, 275, 31, 31))
        self.add_fee_button.setObjectName(_fromUtf8("add_fee_button"))
        self.delete_fee_button = QtGui.QPushButton(self.tab_2)
        self.delete_fee_button.setGeometry(QtCore.QRect(740, 315, 31, 31))
        self.delete_fee_button.setObjectName(_fromUtf8("delete_fee_button"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(460, 70, 310, 140))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.update_records_button = QtGui.QPushButton(self.groupBox_4)
        self.update_records_button.setGeometry(QtCore.QRect(160, 65, 140, 23))
        self.update_records_button.setObjectName(_fromUtf8("update_records_button"))
        self.update_tax_date = QtGui.QDateEdit(self.groupBox_4)
        self.update_tax_date.setGeometry(QtCore.QRect(19, 66, 130, 22))
        self.update_tax_date.setKeyboardTracking(True)
        self.update_tax_date.setCalendarPopup(True)
        self.update_tax_date.setTimeSpec(QtCore.Qt.LocalTime)
        self.update_tax_date.setObjectName(_fromUtf8("update_tax_date"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(270, 70, 150, 140))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(15, 25, 130, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(15, 64, 130, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.from_zone_tax_cbox = QtGui.QComboBox(self.groupBox_5)
        self.from_zone_tax_cbox.setGeometry(QtCore.QRect(10, 40, 130, 22))
        self.from_zone_tax_cbox.setObjectName(_fromUtf8("from_zone_tax_cbox"))
        self.to_zone_tax_cbox = QtGui.QComboBox(self.groupBox_5)
        self.to_zone_tax_cbox.setGeometry(QtCore.QRect(10, 80, 130, 22))
        self.to_zone_tax_cbox.setObjectName(_fromUtf8("to_zone_tax_cbox"))
        self.copy_taxes_button = QtGui.QPushButton(self.groupBox_5)
        self.copy_taxes_button.setGeometry(QtCore.QRect(10, 110, 131, 23))
        self.copy_taxes_button.setObjectName(_fromUtf8("copy_taxes_button"))
        self.zone_location_tax_cbox = QtGui.QComboBox(self.tab_3)
        self.zone_location_tax_cbox.setGeometry(QtCore.QRect(15, 30, 216, 22))
        self.zone_location_tax_cbox.setObjectName(_fromUtf8("zone_location_tax_cbox"))
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(20, 15, 210, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setGeometry(QtCore.QRect(20, 65, 210, 13))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.land_tax_twidget = QtGui.QTableWidget(self.tab_3)
        self.land_tax_twidget.setGeometry(QtCore.QRect(20, 220, 706, 161))
        self.land_tax_twidget.setMinimumSize(QtCore.QSize(440, 0))
        self.land_tax_twidget.setAutoFillBackground(True)
        self.land_tax_twidget.setObjectName(_fromUtf8("land_tax_twidget"))
        self.land_tax_twidget.setColumnCount(5)
        self.land_tax_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        font.setItalic(False)
        item.setFont(font)
        self.land_tax_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        font.setItalic(False)
        item.setFont(font)
        self.land_tax_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.land_tax_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.land_tax_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.land_tax_twidget.setHorizontalHeaderItem(4, item)
        self.land_tax_twidget.horizontalHeader().setCascadingSectionResizes(True)
        self.land_tax_twidget.horizontalHeader().setDefaultSectionSize(200)
        self.land_tax_twidget.horizontalHeader().setHighlightSections(False)
        self.land_tax_twidget.horizontalHeader().setMinimumSectionSize(30)
        self.land_tax_twidget.horizontalHeader().setSortIndicatorShown(False)
        self.land_tax_twidget.horizontalHeader().setStretchLastSection(False)
        self.land_tax_twidget.verticalHeader().setCascadingSectionResizes(True)
        self.land_tax_twidget.verticalHeader().setHighlightSections(True)
        self.land_tax_twidget.verticalHeader().setMinimumSectionSize(25)
        self.land_tax_twidget.verticalHeader().setSortIndicatorShown(False)
        self.land_tax_twidget.verticalHeader().setStretchLastSection(False)
        self.zones_tax_lwidget = QtGui.QListWidget(self.tab_3)
        self.zones_tax_lwidget.setGeometry(QtCore.QRect(20, 80, 210, 130))
        self.zones_tax_lwidget.setObjectName(_fromUtf8("zones_tax_lwidget"))
        self.delete_tax_button = QtGui.QPushButton(self.tab_3)
        self.delete_tax_button.setGeometry(QtCore.QRect(740, 315, 31, 31))
        self.delete_tax_button.setObjectName(_fromUtf8("delete_tax_button"))
        self.add_tax_button = QtGui.QPushButton(self.tab_3)
        self.add_tax_button.setGeometry(QtCore.QRect(740, 275, 31, 31))
        self.add_tax_button.setObjectName(_fromUtf8("add_tax_button"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(7, 5, 766, 91))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_25 = QtGui.QLabel(self.groupBox_6)
        self.label_25.setGeometry(QtCore.QRect(40, 30, 210, 17))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_6)
        self.label_26.setGeometry(QtCore.QRect(280, 30, 210, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        self.label_27.setGeometry(QtCore.QRect(520, 30, 210, 17))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.mn_citizen_first_number_spinbox = QtGui.QSpinBox(self.groupBox_6)
        self.mn_citizen_first_number_spinbox.setGeometry(QtCore.QRect(40, 45, 211, 24))
        self.mn_citizen_first_number_spinbox.setMaximum(2147483644)
        self.mn_citizen_first_number_spinbox.setObjectName(_fromUtf8("mn_citizen_first_number_spinbox"))
        self.mn_citizen_last_number_spinbox = QtGui.QSpinBox(self.groupBox_6)
        self.mn_citizen_last_number_spinbox.setGeometry(QtCore.QRect(280, 45, 211, 24))
        self.mn_citizen_last_number_spinbox.setMaximum(2147483645)
        self.mn_citizen_last_number_spinbox.setObjectName(_fromUtf8("mn_citizen_last_number_spinbox"))
        self.mn_citizen_current_number_ledit = QtGui.QLineEdit(self.groupBox_6)
        self.mn_citizen_current_number_ledit.setGeometry(QtCore.QRect(520, 45, 196, 21))
        self.mn_citizen_current_number_ledit.setReadOnly(True)
        self.mn_citizen_current_number_ledit.setObjectName(_fromUtf8("mn_citizen_current_number_ledit"))
        self.groupBox_11 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_11.setGeometry(QtCore.QRect(7, 100, 766, 91))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.label_29 = QtGui.QLabel(self.groupBox_11)
        self.label_29.setGeometry(QtCore.QRect(40, 30, 210, 17))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.groupBox_11)
        self.label_30.setGeometry(QtCore.QRect(280, 30, 210, 17))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.groupBox_11)
        self.label_31.setGeometry(QtCore.QRect(520, 30, 210, 17))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.mn_business_first_number_spinbox = QtGui.QSpinBox(self.groupBox_11)
        self.mn_business_first_number_spinbox.setGeometry(QtCore.QRect(40, 45, 211, 24))
        self.mn_business_first_number_spinbox.setMaximum(2147483644)
        self.mn_business_first_number_spinbox.setObjectName(_fromUtf8("mn_business_first_number_spinbox"))
        self.mn_business_last_number_spinbox = QtGui.QSpinBox(self.groupBox_11)
        self.mn_business_last_number_spinbox.setGeometry(QtCore.QRect(280, 45, 211, 24))
        self.mn_business_last_number_spinbox.setMaximum(2147483645)
        self.mn_business_last_number_spinbox.setObjectName(_fromUtf8("mn_business_last_number_spinbox"))
        self.mn_business_current_number_ledit = QtGui.QLineEdit(self.groupBox_11)
        self.mn_business_current_number_ledit.setGeometry(QtCore.QRect(520, 45, 196, 21))
        self.mn_business_current_number_ledit.setReadOnly(True)
        self.mn_business_current_number_ledit.setObjectName(_fromUtf8("mn_business_current_number_ledit"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_13.setGeometry(QtCore.QRect(7, 195, 766, 91))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.label_32 = QtGui.QLabel(self.groupBox_13)
        self.label_32.setGeometry(QtCore.QRect(40, 30, 210, 17))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.groupBox_13)
        self.label_33.setGeometry(QtCore.QRect(280, 30, 210, 17))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_34 = QtGui.QLabel(self.groupBox_13)
        self.label_34.setGeometry(QtCore.QRect(520, 30, 210, 17))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.foreign_first_number_spinbox = QtGui.QSpinBox(self.groupBox_13)
        self.foreign_first_number_spinbox.setGeometry(QtCore.QRect(40, 45, 211, 24))
        self.foreign_first_number_spinbox.setMaximum(2147483644)
        self.foreign_first_number_spinbox.setObjectName(_fromUtf8("foreign_first_number_spinbox"))
        self.foreign_last_number_spinbox = QtGui.QSpinBox(self.groupBox_13)
        self.foreign_last_number_spinbox.setGeometry(QtCore.QRect(280, 45, 211, 24))
        self.foreign_last_number_spinbox.setMaximum(2147483645)
        self.foreign_last_number_spinbox.setObjectName(_fromUtf8("foreign_last_number_spinbox"))
        self.foreign_current_number_ledit = QtGui.QLineEdit(self.groupBox_13)
        self.foreign_current_number_ledit.setGeometry(QtCore.QRect(520, 45, 196, 21))
        self.foreign_current_number_ledit.setReadOnly(True)
        self.foreign_current_number_ledit.setObjectName(_fromUtf8("foreign_current_number_ledit"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_14.setGeometry(QtCore.QRect(7, 290, 766, 91))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.label_35 = QtGui.QLabel(self.groupBox_14)
        self.label_35.setGeometry(QtCore.QRect(40, 30, 210, 17))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.groupBox_14)
        self.label_36.setGeometry(QtCore.QRect(280, 30, 210, 17))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.groupBox_14)
        self.label_37.setGeometry(QtCore.QRect(520, 30, 210, 17))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.mn_org_first_number_spinbox = QtGui.QSpinBox(self.groupBox_14)
        self.mn_org_first_number_spinbox.setGeometry(QtCore.QRect(40, 45, 211, 24))
        self.mn_org_first_number_spinbox.setMaximum(2147483644)
        self.mn_org_first_number_spinbox.setObjectName(_fromUtf8("mn_org_first_number_spinbox"))
        self.mn_org_last_number_spinbox = QtGui.QSpinBox(self.groupBox_14)
        self.mn_org_last_number_spinbox.setGeometry(QtCore.QRect(280, 45, 211, 24))
        self.mn_org_last_number_spinbox.setMaximum(2147483645)
        self.mn_org_last_number_spinbox.setObjectName(_fromUtf8("mn_org_last_number_spinbox"))
        self.mn_org_current_number_ledit = QtGui.QLineEdit(self.groupBox_14)
        self.mn_org_current_number_ledit.setGeometry(QtCore.QRect(520, 45, 196, 21))
        self.mn_org_current_number_ledit.setReadOnly(True)
        self.mn_org_current_number_ledit.setObjectName(_fromUtf8("mn_org_current_number_ledit"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.documents_tab = QtGui.QWidget()
        self.documents_tab.setObjectName(_fromUtf8("documents_tab"))
        self.groupBox_12 = QtGui.QGroupBox(self.documents_tab)
        self.groupBox_12.setGeometry(QtCore.QRect(5, 10, 766, 356))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.doc_twidget = QtGui.QTableWidget(self.groupBox_12)
        self.doc_twidget.setGeometry(QtCore.QRect(20, 40, 701, 301))
        self.doc_twidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.doc_twidget.setObjectName(_fromUtf8("doc_twidget"))
        self.doc_twidget.setColumnCount(5)
        self.doc_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.doc_twidget.setHorizontalHeaderItem(4, item)
        self.doc_twidget.horizontalHeader().setCascadingSectionResizes(False)
        self.doc_twidget.horizontalHeader().setDefaultSectionSize(120)
        self.doc_twidget.horizontalHeader().setHighlightSections(False)
        self.doc_twidget.verticalHeader().setCascadingSectionResizes(False)
        self.add_document_button = QtGui.QPushButton(self.groupBox_12)
        self.add_document_button.setGeometry(QtCore.QRect(730, 150, 31, 31))
        self.add_document_button.setObjectName(_fromUtf8("add_document_button"))
        self.remove_document_button = QtGui.QPushButton(self.groupBox_12)
        self.remove_document_button.setGeometry(QtCore.QRect(730, 190, 31, 31))
        self.remove_document_button.setObjectName(_fromUtf8("remove_document_button"))
        self.tabWidget.addTab(self.documents_tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_7.setGeometry(QtCore.QRect(7, 3, 766, 321))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(100, 50, 250, 81))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_8 = QtGui.QLabel(self.groupBox_8)
        self.label_8.setGeometry(QtCore.QRect(20, 25, 210, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.fee_finerate_spinbox = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.fee_finerate_spinbox.setGeometry(QtCore.QRect(20, 40, 221, 24))
        self.fee_finerate_spinbox.setObjectName(_fromUtf8("fee_finerate_spinbox"))
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_9.setGeometry(QtCore.QRect(400, 50, 250, 81))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_9)
        self.label_10.setGeometry(QtCore.QRect(20, 25, 210, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tax_finerate_spinbox = QtGui.QDoubleSpinBox(self.groupBox_9)
        self.tax_finerate_spinbox.setGeometry(QtCore.QRect(20, 40, 221, 24))
        self.tax_finerate_spinbox.setObjectName(_fromUtf8("tax_finerate_spinbox"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_10.setGeometry(QtCore.QRect(6, 3, 766, 376))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_10)
        self.label_11.setGeometry(QtCore.QRect(25, 25, 300, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.select_codelist_cbox = QtGui.QComboBox(self.groupBox_10)
        self.select_codelist_cbox.setGeometry(QtCore.QRect(20, 40, 686, 22))
        self.select_codelist_cbox.setObjectName(_fromUtf8("select_codelist_cbox"))
        self.label_12 = QtGui.QLabel(self.groupBox_10)
        self.label_12.setGeometry(QtCore.QRect(20, 70, 300, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.groupBox_10)
        self.label_13.setGeometry(QtCore.QRect(30, 400, 101, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.delete_button = QtGui.QPushButton(self.groupBox_10)
        self.delete_button.setGeometry(QtCore.QRect(725, 230, 31, 31))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.add_button = QtGui.QPushButton(self.groupBox_10)
        self.add_button.setGeometry(QtCore.QRect(725, 190, 31, 31))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.table_widget = QtGui.QTableWidget(self.groupBox_10)
        self.table_widget.setGeometry(QtCore.QRect(20, 85, 691, 281))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_widget.sizePolicy().hasHeightForWidth())
        self.table_widget.setSizePolicy(sizePolicy)
        self.table_widget.setObjectName(_fromUtf8("table_widget"))
        self.table_widget.setColumnCount(2)
        self.table_widget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_widget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_widget.setHorizontalHeaderItem(1, item)
        self.table_widget.horizontalHeader().setDefaultSectionSize(80)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.company_twidget = QtGui.QTableWidget(self.tab)
        self.company_twidget.setGeometry(QtCore.QRect(20, 45, 706, 161))
        self.company_twidget.setMinimumSize(QtCore.QSize(441, 0))
        self.company_twidget.setAutoFillBackground(True)
        self.company_twidget.setObjectName(_fromUtf8("company_twidget"))
        self.company_twidget.setColumnCount(2)
        self.company_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.company_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.company_twidget.setHorizontalHeaderItem(1, item)
        self.company_twidget.horizontalHeader().setCascadingSectionResizes(True)
        self.company_twidget.horizontalHeader().setDefaultSectionSize(200)
        self.company_twidget.horizontalHeader().setHighlightSections(False)
        self.company_twidget.horizontalHeader().setMinimumSectionSize(30)
        self.company_twidget.horizontalHeader().setSortIndicatorShown(False)
        self.company_twidget.horizontalHeader().setStretchLastSection(False)
        self.company_twidget.verticalHeader().setCascadingSectionResizes(True)
        self.company_twidget.verticalHeader().setHighlightSections(True)
        self.company_twidget.verticalHeader().setMinimumSectionSize(25)
        self.company_twidget.verticalHeader().setSortIndicatorShown(False)
        self.company_twidget.verticalHeader().setStretchLastSection(False)
        self.surveyor_twidget = QtGui.QTableWidget(self.tab)
        self.surveyor_twidget.setGeometry(QtCore.QRect(20, 225, 706, 161))
        self.surveyor_twidget.setMinimumSize(QtCore.QSize(441, 0))
        self.surveyor_twidget.setAutoFillBackground(True)
        self.surveyor_twidget.setObjectName(_fromUtf8("surveyor_twidget"))
        self.surveyor_twidget.setColumnCount(3)
        self.surveyor_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.surveyor_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.surveyor_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Grande"))
        font.setPointSize(8)
        item.setFont(font)
        self.surveyor_twidget.setHorizontalHeaderItem(2, item)
        self.surveyor_twidget.horizontalHeader().setCascadingSectionResizes(True)
        self.surveyor_twidget.horizontalHeader().setDefaultSectionSize(200)
        self.surveyor_twidget.horizontalHeader().setHighlightSections(False)
        self.surveyor_twidget.horizontalHeader().setMinimumSectionSize(30)
        self.surveyor_twidget.horizontalHeader().setSortIndicatorShown(False)
        self.surveyor_twidget.horizontalHeader().setStretchLastSection(False)
        self.surveyor_twidget.verticalHeader().setCascadingSectionResizes(True)
        self.surveyor_twidget.verticalHeader().setHighlightSections(True)
        self.surveyor_twidget.verticalHeader().setMinimumSectionSize(25)
        self.surveyor_twidget.verticalHeader().setSortIndicatorShown(False)
        self.surveyor_twidget.verticalHeader().setStretchLastSection(False)
        self.add_company_button = QtGui.QPushButton(self.tab)
        self.add_company_button.setGeometry(QtCore.QRect(740, 75, 31, 31))
        self.add_company_button.setObjectName(_fromUtf8("add_company_button"))
        self.delete_company_button = QtGui.QPushButton(self.tab)
        self.delete_company_button.setGeometry(QtCore.QRect(740, 115, 31, 31))
        self.delete_company_button.setObjectName(_fromUtf8("delete_company_button"))
        self.add_surveyor_button = QtGui.QPushButton(self.tab)
        self.add_surveyor_button.setGeometry(QtCore.QRect(740, 270, 31, 31))
        self.add_surveyor_button.setObjectName(_fromUtf8("add_surveyor_button"))
        self.delete_surveyor_button = QtGui.QPushButton(self.tab)
        self.delete_surveyor_button.setGeometry(QtCore.QRect(740, 310, 31, 31))
        self.delete_surveyor_button.setObjectName(_fromUtf8("delete_surveyor_button"))
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(20, 30, 706, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_28 = QtGui.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(20, 210, 210, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.find_company_button = QtGui.QPushButton(self.tab)
        self.find_company_button.setGeometry(QtCore.QRect(590, 5, 114, 23))
        self.find_company_button.setObjectName(_fromUtf8("find_company_button"))
        self.company_ledit = QtGui.QLineEdit(self.tab)
        self.company_ledit.setGeometry(QtCore.QRect(350, 6, 226, 20))
        self.company_ledit.setObjectName(_fromUtf8("company_ledit"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(185, 9, 156, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.Other = QtGui.QWidget()
        self.Other.setObjectName(_fromUtf8("Other"))
        self.logging_chk_box = QtGui.QGroupBox(self.Other)
        self.logging_chk_box.setGeometry(QtCore.QRect(6, 4, 766, 271))
        self.logging_chk_box.setObjectName(_fromUtf8("logging_chk_box"))
        self.checkBox = QtGui.QCheckBox(self.logging_chk_box)
        self.checkBox.setGeometry(QtCore.QRect(95, 85, 196, 18))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.tabWidget.addTab(self.Other, _fromUtf8(""))
        self.Equipmentlist = QtGui.QWidget()
        self.Equipmentlist.setObjectName(_fromUtf8("Equipmentlist"))
        self.equipment_twidget = QtGui.QTableWidget(self.Equipmentlist)
        self.equipment_twidget.setGeometry(QtCore.QRect(5, 229, 772, 156))
        self.equipment_twidget.setObjectName(_fromUtf8("equipment_twidget"))
        self.equipment_twidget.setColumnCount(9)
        self.equipment_twidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.equipment_twidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_twidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_twidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_twidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_twidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_twidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_twidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_twidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.equipment_twidget.setHorizontalHeaderItem(8, item)
        self.groupBox_15 = QtGui.QGroupBox(self.Equipmentlist)
        self.groupBox_15.setGeometry(QtCore.QRect(5, 1, 771, 222))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.label_40 = QtGui.QLabel(self.groupBox_15)
        self.label_40.setGeometry(QtCore.QRect(235, 16, 200, 16))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.id_equipment_edit = QtGui.QLineEdit(self.groupBox_15)
        self.id_equipment_edit.setGeometry(QtCore.QRect(680, 34, 81, 20))
        self.id_equipment_edit.setReadOnly(True)
        self.id_equipment_edit.setObjectName(_fromUtf8("id_equipment_edit"))
        self.label_15 = QtGui.QLabel(self.groupBox_15)
        self.label_15.setGeometry(QtCore.QRect(10, 103, 106, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.given_date = QtGui.QDateEdit(self.groupBox_15)
        self.given_date.setGeometry(QtCore.QRect(10, 121, 110, 22))
        self.given_date.setObjectName(_fromUtf8("given_date"))
        self.duration_date = QtGui.QDateEdit(self.groupBox_15)
        self.duration_date.setGeometry(QtCore.QRect(10, 164, 110, 22))
        self.duration_date.setObjectName(_fromUtf8("duration_date"))
        self.documents_groupbox = QtGui.QGroupBox(self.groupBox_15)
        self.documents_groupbox.setGeometry(QtCore.QRect(455, 61, 306, 151))
        self.documents_groupbox.setObjectName(_fromUtf8("documents_groupbox"))
        self.equipment_doc_twidget = QtGui.QListWidget(self.documents_groupbox)
        self.equipment_doc_twidget.setGeometry(QtCore.QRect(6, 20, 205, 121))
        self.equipment_doc_twidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.equipment_doc_twidget.setObjectName(_fromUtf8("equipment_doc_twidget"))
        self.add_equip_doc_button = QtGui.QPushButton(self.documents_groupbox)
        self.add_equip_doc_button.setEnabled(False)
        self.add_equip_doc_button.setGeometry(QtCore.QRect(218, 37, 81, 23))
        self.add_equip_doc_button.setObjectName(_fromUtf8("add_equip_doc_button"))
        self.delete_equip_doc_button = QtGui.QPushButton(self.documents_groupbox)
        self.delete_equip_doc_button.setEnabled(False)
        self.delete_equip_doc_button.setGeometry(QtCore.QRect(218, 102, 81, 23))
        self.delete_equip_doc_button.setObjectName(_fromUtf8("delete_equip_doc_button"))
        self.view_equip_doc_button = QtGui.QPushButton(self.documents_groupbox)
        self.view_equip_doc_button.setEnabled(False)
        self.view_equip_doc_button.setGeometry(QtCore.QRect(218, 70, 81, 23))
        self.view_equip_doc_button.setObjectName(_fromUtf8("view_equip_doc_button"))
        self.label_41 = QtGui.QLabel(self.groupBox_15)
        self.label_41.setGeometry(QtCore.QRect(455, 16, 200, 16))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.equipment_list_cbox = QtGui.QComboBox(self.groupBox_15)
        self.equipment_list_cbox.setGeometry(QtCore.QRect(10, 33, 200, 22))
        self.equipment_list_cbox.setObjectName(_fromUtf8("equipment_list_cbox"))
        self.initial_date = QtGui.QDateEdit(self.groupBox_15)
        self.initial_date.setGeometry(QtCore.QRect(10, 78, 110, 22))
        self.initial_date.setObjectName(_fromUtf8("initial_date"))
        self.seller_name_edit = QtGui.QLineEdit(self.groupBox_15)
        self.seller_name_edit.setGeometry(QtCore.QRect(455, 34, 211, 20))
        self.seller_name_edit.setObjectName(_fromUtf8("seller_name_edit"))
        self.add_equipment_button = QtGui.QPushButton(self.groupBox_15)
        self.add_equipment_button.setGeometry(QtCore.QRect(165, 191, 75, 23))
        self.add_equipment_button.setObjectName(_fromUtf8("add_equipment_button"))
        self.mac_address_edit = QtGui.QLineEdit(self.groupBox_15)
        self.mac_address_edit.setGeometry(QtCore.QRect(140, 79, 296, 20))
        self.mac_address_edit.setObjectName(_fromUtf8("mac_address_edit"))
        self.delete_equipment_button = QtGui.QPushButton(self.groupBox_15)
        self.delete_equipment_button.setGeometry(QtCore.QRect(361, 191, 75, 23))
        self.delete_equipment_button.setObjectName(_fromUtf8("delete_equipment_button"))
        self.equipment_desc_text = QtGui.QTextEdit(self.groupBox_15)
        self.equipment_desc_text.setGeometry(QtCore.QRect(140, 123, 296, 61))
        self.equipment_desc_text.setObjectName(_fromUtf8("equipment_desc_text"))
        self.label_39 = QtGui.QLabel(self.groupBox_15)
        self.label_39.setGeometry(QtCore.QRect(10, 16, 200, 16))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.edit_equipment_button = QtGui.QPushButton(self.groupBox_15)
        self.edit_equipment_button.setGeometry(QtCore.QRect(264, 191, 75, 23))
        self.edit_equipment_button.setObjectName(_fromUtf8("edit_equipment_button"))
        self.label_38 = QtGui.QLabel(self.groupBox_15)
        self.label_38.setGeometry(QtCore.QRect(10, 146, 116, 16))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_44 = QtGui.QLabel(self.groupBox_15)
        self.label_44.setGeometry(QtCore.QRect(680, 16, 46, 13))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.users_list_cbox = QtGui.QComboBox(self.groupBox_15)
        self.users_list_cbox.setGeometry(QtCore.QRect(235, 33, 200, 22))
        self.users_list_cbox.setObjectName(_fromUtf8("users_list_cbox"))
        self.label_43 = QtGui.QLabel(self.groupBox_15)
        self.label_43.setGeometry(QtCore.QRect(140, 61, 121, 16))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.label_42 = QtGui.QLabel(self.groupBox_15)
        self.label_42.setGeometry(QtCore.QRect(141, 103, 161, 16))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_14 = QtGui.QLabel(self.groupBox_15)
        self.label_14.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.tabWidget.addTab(self.Equipmentlist, _fromUtf8(""))
        self.status_label = QtGui.QLabel(LandOfficeAdministrativeSettingsDialog)
        self.status_label.setGeometry(QtCore.QRect(20, 435, 486, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Gothic"))
        font.setBold(True)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName(_fromUtf8("status_label"))
        self.apply_button = QtGui.QPushButton(LandOfficeAdministrativeSettingsDialog)
        self.apply_button.setGeometry(QtCore.QRect(630, 430, 75, 23))
        self.apply_button.setObjectName(_fromUtf8("apply_button"))

        self.retranslateUi(LandOfficeAdministrativeSettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LandOfficeAdministrativeSettingsDialog)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.tabWidget, self.land_office_name_edit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.land_office_name_edit, self.address_edit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.address_edit, self.bank_cbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.bank_cbox, self.bank_account_num_edit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.bank_account_num_edit, self.phone_edit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.phone_edit, self.fax_edit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.fax_edit, self.email_address_edit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.email_address_edit, self.web_site_edit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.web_site_edit, self.apply_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.apply_button, self.close_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.close_button, self.help_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.help_button, self.zone_location_cbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.zone_location_cbox, self.zones_lwidget)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.zones_lwidget, self.from_zone_cbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.from_zone_cbox, self.to_zone_cbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.to_zone_cbox, self.copy_fees_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.copy_fees_button, self.update_date)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.update_date, self.update_contracts_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.update_contracts_button, self.land_fee_twidget)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.land_fee_twidget, self.add_fee_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.add_fee_button, self.delete_fee_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.delete_fee_button, self.zone_location_tax_cbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.zone_location_tax_cbox, self.zones_tax_lwidget)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.zones_tax_lwidget, self.from_zone_tax_cbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.from_zone_tax_cbox, self.to_zone_tax_cbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.to_zone_tax_cbox, self.copy_taxes_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.copy_taxes_button, self.update_tax_date)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.update_tax_date, self.update_records_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.update_records_button, self.land_tax_twidget)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.land_tax_twidget, self.add_tax_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.add_tax_button, self.delete_tax_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.delete_tax_button, self.mn_citizen_first_number_spinbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.mn_citizen_first_number_spinbox, self.mn_citizen_last_number_spinbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.mn_citizen_last_number_spinbox, self.mn_citizen_current_number_ledit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.mn_citizen_current_number_ledit, self.mn_business_first_number_spinbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.mn_business_first_number_spinbox, self.mn_business_last_number_spinbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.mn_business_last_number_spinbox, self.mn_business_current_number_ledit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.mn_business_current_number_ledit, self.foreign_first_number_spinbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.foreign_first_number_spinbox, self.foreign_last_number_spinbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.foreign_last_number_spinbox, self.foreign_current_number_ledit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.foreign_current_number_ledit, self.mn_org_first_number_spinbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.mn_org_first_number_spinbox, self.mn_org_last_number_spinbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.mn_org_last_number_spinbox, self.mn_org_current_number_ledit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.mn_org_current_number_ledit, self.doc_twidget)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.doc_twidget, self.add_document_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.add_document_button, self.remove_document_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.remove_document_button, self.fee_finerate_spinbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.fee_finerate_spinbox, self.tax_finerate_spinbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.tax_finerate_spinbox, self.select_codelist_cbox)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.select_codelist_cbox, self.table_widget)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.table_widget, self.add_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.add_button, self.delete_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.delete_button, self.company_ledit)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.company_ledit, self.find_company_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.find_company_button, self.company_twidget)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.company_twidget, self.add_company_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.add_company_button, self.delete_company_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.delete_company_button, self.surveyor_twidget)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.surveyor_twidget, self.add_surveyor_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.add_surveyor_button, self.delete_surveyor_button)
        LandOfficeAdministrativeSettingsDialog.setTabOrder(self.delete_surveyor_button, self.checkBox)

    def retranslateUi(self, LandOfficeAdministrativeSettingsDialog):
        LandOfficeAdministrativeSettingsDialog.setWindowTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Administrative Settings", None))
        self.close_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Close", None))
        self.help_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "?", None))
        self.groupBox.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Land Office", None))
        self.label.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Land Office Name", None))
        self.label_2.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Address", None))
        self.label_3.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Bank", None))
        self.label_4.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Bank Account Number", None))
        self.label_5.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Phone", None))
        self.label_6.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Fax", None))
        self.label_7.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Email Address", None))
        self.web_site_label.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Website", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("LandOfficeAdministrativeSettingsDialog", "Report Parameters", None))
        self.label_16.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Zone Location", None))
        self.label_17.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Zones", None))
        self.groupBox_2.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Copy Fee Entries", None))
        self.label_18.setText(_translate("LandOfficeAdministrativeSettingsDialog", "From Zone", None))
        self.label_19.setText(_translate("LandOfficeAdministrativeSettingsDialog", "To Zone", None))
        self.copy_fees_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Copy", None))
        self.groupBox_3.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "New Decision Or Change Of Zone Boundary", None))
        self.update_contracts_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Update Contracts", None))
        self.update_date.setDisplayFormat(_translate("LandOfficeAdministrativeSettingsDialog", "yyyy-MM-dd", None))
        item = self.land_fee_twidget.horizontalHeaderItem(0)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Land Use Category", None))
        item = self.land_fee_twidget.horizontalHeaderItem(1)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Fee Per m2 (₮)", None))
        item = self.land_fee_twidget.horizontalHeaderItem(2)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Subsidized Area (m2)", None))
        item = self.land_fee_twidget.horizontalHeaderItem(3)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Subsidized Fee Rate (%)", None))
        self.add_fee_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Add Row", None))
        self.add_fee_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "+", None))
        self.delete_fee_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Delete Row", None))
        self.delete_fee_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LandOfficeAdministrativeSettingsDialog", "Land Fee Base Values", None))
        self.groupBox_4.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "New Decision Or Change Of Zone Boundary", None))
        self.update_records_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Update Records", None))
        self.update_tax_date.setDisplayFormat(_translate("LandOfficeAdministrativeSettingsDialog", "yyyy-MM-dd", None))
        self.groupBox_5.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Copy Zone Entries", None))
        self.label_21.setText(_translate("LandOfficeAdministrativeSettingsDialog", "From Zone", None))
        self.label_22.setText(_translate("LandOfficeAdministrativeSettingsDialog", "To Zone", None))
        self.copy_taxes_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Copy", None))
        self.label_23.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Zone Location", None))
        self.label_24.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Zones", None))
        item = self.land_tax_twidget.horizontalHeaderItem(0)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Land Use Category", None))
        item = self.land_tax_twidget.horizontalHeaderItem(1)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Base Value Per m2 (₮)", None))
        item = self.land_tax_twidget.horizontalHeaderItem(2)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Base Tax Rate (%)", None))
        item = self.land_tax_twidget.horizontalHeaderItem(3)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Subsidized Area (m2)", None))
        item = self.land_tax_twidget.horizontalHeaderItem(4)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Subsidized Tax Rate (%)", None))
        self.delete_tax_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Delete Row", None))
        self.delete_tax_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "-", None))
        self.add_tax_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Add Row", None))
        self.add_tax_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "+", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("LandOfficeAdministrativeSettingsDialog", "Land Base Values And Land Tax", None))
        self.groupBox_6.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Range Of Certificate Numbers for Mongolian Citizens", None))
        self.label_25.setText(_translate("LandOfficeAdministrativeSettingsDialog", "First Number", None))
        self.label_26.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Last Number", None))
        self.label_27.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Current Number (Last Used)", None))
        self.groupBox_11.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Range Of Certificate Numbers for Mongolian Business Entities", None))
        self.label_29.setText(_translate("LandOfficeAdministrativeSettingsDialog", "First Number", None))
        self.label_30.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Last Number", None))
        self.label_31.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Current Number (Last Used)", None))
        self.groupBox_13.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Range Of Certificate Numbers for Foreign Citizens and Entities", None))
        self.label_32.setText(_translate("LandOfficeAdministrativeSettingsDialog", "First Number", None))
        self.label_33.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Last Number", None))
        self.label_34.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Current Number (Last Used)", None))
        self.groupBox_14.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Range Of Certificate Numbers for Mongolian State Organizations", None))
        self.label_35.setText(_translate("LandOfficeAdministrativeSettingsDialog", "First Number", None))
        self.label_36.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Last Number", None))
        self.label_37.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Current Number (Last Used)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("LandOfficeAdministrativeSettingsDialog", "Certificates Numbers", None))
        self.groupBox_12.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Official documents", None))
        item = self.doc_twidget.horizontalHeaderItem(0)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Visible", None))
        item = self.doc_twidget.horizontalHeaderItem(1)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Name", None))
        item = self.doc_twidget.horizontalHeaderItem(2)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Description", None))
        item = self.doc_twidget.horizontalHeaderItem(3)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Open", None))
        item = self.doc_twidget.horizontalHeaderItem(4)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "View", None))
        self.add_document_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Add Row", None))
        self.add_document_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "+", None))
        self.remove_document_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Delete Row", None))
        self.remove_document_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documents_tab), _translate("LandOfficeAdministrativeSettingsDialog", "Official Documents", None))
        self.groupBox_7.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Interest Rates For Delayed Payments", None))
        self.groupBox_8.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Land Fee", None))
        self.label_8.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Rate Per Day (%)", None))
        self.groupBox_9.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Land Tax", None))
        self.label_10.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Rate Per Day (%)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("LandOfficeAdministrativeSettingsDialog", "Payments", None))
        self.groupBox_10.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Codelists", None))
        self.label_11.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Select Codelist", None))
        self.label_12.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Entries", None))
        self.label_13.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Messages", None))
        self.delete_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Delete Row", None))
        self.delete_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "-", None))
        self.add_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Add Row", None))
        self.add_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "+", None))
        item = self.table_widget.horizontalHeaderItem(0)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Code", None))
        item = self.table_widget.horizontalHeaderItem(1)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Description", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("LandOfficeAdministrativeSettingsDialog", "Codelists", None))
        item = self.company_twidget.horizontalHeaderItem(0)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Name", None))
        item = self.company_twidget.horizontalHeaderItem(1)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Address", None))
        item = self.surveyor_twidget.horizontalHeaderItem(0)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Surname", None))
        item = self.surveyor_twidget.horizontalHeaderItem(1)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "First Name", None))
        item = self.surveyor_twidget.horizontalHeaderItem(2)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Phone", None))
        self.add_company_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Add Row", None))
        self.add_company_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "+", None))
        self.delete_company_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Delete Row", None))
        self.delete_company_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "-", None))
        self.add_surveyor_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Add Row", None))
        self.add_surveyor_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "+", None))
        self.delete_surveyor_button.setToolTip(_translate("LandOfficeAdministrativeSettingsDialog", "Delete Row", None))
        self.delete_surveyor_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "-", None))
        self.label_20.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Companies", None))
        self.label_28.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Surveyors", None))
        self.find_company_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Find", None))
        self.label_9.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Company Name/Address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("LandOfficeAdministrativeSettingsDialog", "Survey Company", None))
        self.logging_chk_box.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Miscellaneous", None))
        self.checkBox.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Log errors and messages", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Other), _translate("LandOfficeAdministrativeSettingsDialog", "Miscellaneous", None))
        item = self.equipment_twidget.horizontalHeaderItem(0)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "ID", None))
        item = self.equipment_twidget.horizontalHeaderItem(1)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Equipment Name", None))
        item = self.equipment_twidget.horizontalHeaderItem(2)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "UserName", None))
        item = self.equipment_twidget.horizontalHeaderItem(3)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Purchase Date", None))
        item = self.equipment_twidget.horizontalHeaderItem(4)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Given Date", None))
        item = self.equipment_twidget.horizontalHeaderItem(5)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Duration Date", None))
        item = self.equipment_twidget.horizontalHeaderItem(6)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Description", None))
        item = self.equipment_twidget.horizontalHeaderItem(7)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Mac Address", None))
        item = self.equipment_twidget.horizontalHeaderItem(8)
        item.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Seller Name", None))
        self.groupBox_15.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Register Information and Find", None))
        self.label_40.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Users List", None))
        self.label_15.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Given to LO Date", None))
        self.documents_groupbox.setTitle(_translate("LandOfficeAdministrativeSettingsDialog", "Attached Document(s)", None))
        self.add_equip_doc_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Add", None))
        self.delete_equip_doc_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Delete", None))
        self.view_equip_doc_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "View", None))
        self.label_41.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Seller Name", None))
        self.add_equipment_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Add", None))
        self.delete_equipment_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Delete", None))
        self.label_39.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Equipment List", None))
        self.edit_equipment_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Edit", None))
        self.label_38.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Valid Duration Date", None))
        self.label_44.setText(_translate("LandOfficeAdministrativeSettingsDialog", "ID", None))
        self.label_43.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Mac Address", None))
        self.label_42.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Description", None))
        self.label_14.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Initial Purchase Date", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Equipmentlist), _translate("LandOfficeAdministrativeSettingsDialog", "Equipment List", None))
        self.status_label.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Messages", None))
        self.apply_button.setText(_translate("LandOfficeAdministrativeSettingsDialog", "Apply", None))

