# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UserRoleManagementDialog.ui'
#
# Created: Tue Nov 03 15:49:11 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UserRoleManagementDialog(object):
    def setupUi(self, UserRoleManagementDialog):
        UserRoleManagementDialog.setObjectName(_fromUtf8("UserRoleManagementDialog"))
        UserRoleManagementDialog.resize(800, 470)
        UserRoleManagementDialog.setMinimumSize(QtCore.QSize(800, 470))
        UserRoleManagementDialog.setMaximumSize(QtCore.QSize(800, 470))
        UserRoleManagementDialog.setBaseSize(QtCore.QSize(860, 470))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/user_role_management.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        UserRoleManagementDialog.setWindowIcon(icon)
        self.groupBox = QtGui.QGroupBox(UserRoleManagementDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 39, 331, 381))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.username_edit = QtGui.QLineEdit(self.groupBox)
        self.username_edit.setGeometry(QtCore.QRect(10, 30, 150, 20))
        self.username_edit.setObjectName(_fromUtf8("username_edit"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 15, 151, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.password_edit = QtGui.QLineEdit(self.groupBox)
        self.password_edit.setGeometry(QtCore.QRect(10, 70, 150, 20))
        self.password_edit.setEchoMode(QtGui.QLineEdit.Password)
        self.password_edit.setObjectName(_fromUtf8("password_edit"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 55, 151, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 95, 151, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.retype_password_edit = QtGui.QLineEdit(self.groupBox)
        self.retype_password_edit.setGeometry(QtCore.QRect(10, 110, 150, 20))
        self.retype_password_edit.setEchoMode(QtGui.QLineEdit.Password)
        self.retype_password_edit.setObjectName(_fromUtf8("retype_password_edit"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 182, 151, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.mac_address_edit = QtGui.QLineEdit(self.groupBox)
        self.mac_address_edit.setGeometry(QtCore.QRect(170, 180, 151, 20))
        self.mac_address_edit.setObjectName(_fromUtf8("mac_address_edit"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(170, 15, 151, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.surname_edit = QtGui.QLineEdit(self.groupBox)
        self.surname_edit.setGeometry(QtCore.QRect(170, 30, 150, 20))
        self.surname_edit.setObjectName(_fromUtf8("surname_edit"))
        self.firstname_edit = QtGui.QLineEdit(self.groupBox)
        self.firstname_edit.setGeometry(QtCore.QRect(170, 70, 150, 20))
        self.firstname_edit.setObjectName(_fromUtf8("firstname_edit"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(170, 55, 151, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 133, 151, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.add_button = QtGui.QPushButton(self.groupBox)
        self.add_button.setGeometry(QtCore.QRect(31, 213, 70, 23))
        self.add_button.setObjectName(_fromUtf8("add_button"))
        self.update_button = QtGui.QPushButton(self.groupBox)
        self.update_button.setGeometry(QtCore.QRect(131, 213, 70, 23))
        self.update_button.setObjectName(_fromUtf8("update_button"))
        self.delete_button = QtGui.QPushButton(self.groupBox)
        self.delete_button.setGeometry(QtCore.QRect(228, 213, 70, 23))
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 311, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(170, 95, 151, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.phone_edit = QtGui.QLineEdit(self.groupBox)
        self.phone_edit.setGeometry(QtCore.QRect(170, 110, 150, 20))
        self.phone_edit.setText(_fromUtf8(""))
        self.phone_edit.setObjectName(_fromUtf8("phone_edit"))
        self.user_role_lwidget = QtGui.QListWidget(self.groupBox)
        self.user_role_lwidget.setGeometry(QtCore.QRect(10, 265, 311, 106))
        self.user_role_lwidget.setObjectName(_fromUtf8("user_role_lwidget"))
        self.position_cbox = QtGui.QComboBox(self.groupBox)
        self.position_cbox.setGeometry(QtCore.QRect(10, 150, 311, 22))
        self.position_cbox.setObjectName(_fromUtf8("position_cbox"))
        self.groupBox_2 = QtGui.QGroupBox(UserRoleManagementDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(350, 39, 230, 381))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 25, 201, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.down_groups_button = QtGui.QPushButton(self.groupBox_2)
        self.down_groups_button.setGeometry(QtCore.QRect(70, 187, 30, 25))
        self.down_groups_button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/down_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_groups_button.setIcon(icon1)
        self.down_groups_button.setObjectName(_fromUtf8("down_groups_button"))
        self.up_groups_button = QtGui.QPushButton(self.groupBox_2)
        self.up_groups_button.setGeometry(QtCore.QRect(116, 187, 30, 25))
        self.up_groups_button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/up_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up_groups_button.setIcon(icon2)
        self.up_groups_button.setObjectName(_fromUtf8("up_groups_button"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 230, 209, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.group_lwidget = QtGui.QListWidget(self.groupBox_2)
        self.group_lwidget.setGeometry(QtCore.QRect(10, 40, 211, 126))
        self.group_lwidget.setObjectName(_fromUtf8("group_lwidget"))
        self.member_lwidget = QtGui.QListWidget(self.groupBox_2)
        self.member_lwidget.setGeometry(QtCore.QRect(10, 245, 211, 126))
        self.member_lwidget.setObjectName(_fromUtf8("member_lwidget"))
        self.line = QtGui.QFrame(UserRoleManagementDialog)
        self.line.setGeometry(QtCore.QRect(0, 20, 798, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_9 = QtGui.QLabel(UserRoleManagementDialog)
        self.label_9.setGeometry(QtCore.QRect(10, 7, 231, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.groupBox_3 = QtGui.QGroupBox(UserRoleManagementDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(590, 39, 204, 381))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(15, 25, 181, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.aimag_cbox = QtGui.QComboBox(self.groupBox_3)
        self.aimag_cbox.setGeometry(QtCore.QRect(10, 40, 184, 22))
        self.aimag_cbox.setObjectName(_fromUtf8("aimag_cbox"))
        self.aimag_lwidget = QtGui.QListWidget(self.groupBox_3)
        self.aimag_lwidget.setGeometry(QtCore.QRect(10, 109, 184, 76))
        self.aimag_lwidget.setObjectName(_fromUtf8("aimag_lwidget"))
        self.down_aimag_button = QtGui.QPushButton(self.groupBox_3)
        self.down_aimag_button.setGeometry(QtCore.QRect(64, 65, 30, 25))
        self.down_aimag_button.setText(_fromUtf8(""))
        self.down_aimag_button.setIcon(icon1)
        self.down_aimag_button.setObjectName(_fromUtf8("down_aimag_button"))
        self.up_aimag_button = QtGui.QPushButton(self.groupBox_3)
        self.up_aimag_button.setGeometry(QtCore.QRect(110, 65, 30, 25))
        self.up_aimag_button.setText(_fromUtf8(""))
        self.up_aimag_button.setIcon(icon2)
        self.up_aimag_button.setObjectName(_fromUtf8("up_aimag_button"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(15, 195, 181, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.soum_cbox = QtGui.QComboBox(self.groupBox_3)
        self.soum_cbox.setGeometry(QtCore.QRect(10, 210, 184, 22))
        self.soum_cbox.setObjectName(_fromUtf8("soum_cbox"))
        self.soum_lwidget = QtGui.QListWidget(self.groupBox_3)
        self.soum_lwidget.setGeometry(QtCore.QRect(10, 280, 184, 91))
        self.soum_lwidget.setObjectName(_fromUtf8("soum_lwidget"))
        self.up_soum_button = QtGui.QPushButton(self.groupBox_3)
        self.up_soum_button.setGeometry(QtCore.QRect(110, 235, 30, 25))
        self.up_soum_button.setText(_fromUtf8(""))
        self.up_soum_button.setIcon(icon2)
        self.up_soum_button.setObjectName(_fromUtf8("up_soum_button"))
        self.down_soum_button = QtGui.QPushButton(self.groupBox_3)
        self.down_soum_button.setGeometry(QtCore.QRect(64, 235, 30, 25))
        self.down_soum_button.setText(_fromUtf8(""))
        self.down_soum_button.setIcon(icon1)
        self.down_soum_button.setObjectName(_fromUtf8("down_soum_button"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 181, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 265, 181, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.close_button = QtGui.QPushButton(UserRoleManagementDialog)
        self.close_button.setGeometry(QtCore.QRect(703, 430, 70, 23))
        self.close_button.setObjectName(_fromUtf8("close_button"))
        self.help_button = QtGui.QPushButton(UserRoleManagementDialog)
        self.help_button.setGeometry(QtCore.QRect(602, 430, 81, 23))
        self.help_button.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/lm2/help_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help_button.setIcon(icon3)
        self.help_button.setObjectName(_fromUtf8("help_button"))
        self.line_2 = QtGui.QFrame(UserRoleManagementDialog)
        self.line_2.setGeometry(QtCore.QRect(0, 450, 799, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))

        self.retranslateUi(UserRoleManagementDialog)
        QtCore.QMetaObject.connectSlotsByName(UserRoleManagementDialog)
        UserRoleManagementDialog.setTabOrder(self.username_edit, self.password_edit)
        UserRoleManagementDialog.setTabOrder(self.password_edit, self.retype_password_edit)
        UserRoleManagementDialog.setTabOrder(self.retype_password_edit, self.mac_address_edit)
        UserRoleManagementDialog.setTabOrder(self.mac_address_edit, self.surname_edit)
        UserRoleManagementDialog.setTabOrder(self.surname_edit, self.firstname_edit)
        UserRoleManagementDialog.setTabOrder(self.firstname_edit, self.phone_edit)
        UserRoleManagementDialog.setTabOrder(self.phone_edit, self.add_button)
        UserRoleManagementDialog.setTabOrder(self.add_button, self.update_button)
        UserRoleManagementDialog.setTabOrder(self.update_button, self.delete_button)
        UserRoleManagementDialog.setTabOrder(self.delete_button, self.user_role_lwidget)
        UserRoleManagementDialog.setTabOrder(self.user_role_lwidget, self.group_lwidget)
        UserRoleManagementDialog.setTabOrder(self.group_lwidget, self.down_groups_button)
        UserRoleManagementDialog.setTabOrder(self.down_groups_button, self.up_groups_button)
        UserRoleManagementDialog.setTabOrder(self.up_groups_button, self.member_lwidget)
        UserRoleManagementDialog.setTabOrder(self.member_lwidget, self.aimag_cbox)
        UserRoleManagementDialog.setTabOrder(self.aimag_cbox, self.down_aimag_button)
        UserRoleManagementDialog.setTabOrder(self.down_aimag_button, self.up_aimag_button)
        UserRoleManagementDialog.setTabOrder(self.up_aimag_button, self.aimag_lwidget)
        UserRoleManagementDialog.setTabOrder(self.aimag_lwidget, self.soum_cbox)
        UserRoleManagementDialog.setTabOrder(self.soum_cbox, self.down_soum_button)
        UserRoleManagementDialog.setTabOrder(self.down_soum_button, self.up_soum_button)
        UserRoleManagementDialog.setTabOrder(self.up_soum_button, self.soum_lwidget)
        UserRoleManagementDialog.setTabOrder(self.soum_lwidget, self.help_button)
        UserRoleManagementDialog.setTabOrder(self.help_button, self.close_button)

    def retranslateUi(self, UserRoleManagementDialog):
        UserRoleManagementDialog.setWindowTitle(_translate("UserRoleManagementDialog", "User Role Management", None))
        self.groupBox.setTitle(_translate("UserRoleManagementDialog", "User Roles", None))
        self.label.setText(_translate("UserRoleManagementDialog", "User Name", None))
        self.label_2.setText(_translate("UserRoleManagementDialog", "Password", None))
        self.label_3.setText(_translate("UserRoleManagementDialog", "Retype Password", None))
        self.label_4.setText(_translate("UserRoleManagementDialog", "MAC Address(es)", None))
        self.label_5.setText(_translate("UserRoleManagementDialog", "Surname", None))
        self.label_6.setText(_translate("UserRoleManagementDialog", "First Name", None))
        self.label_7.setText(_translate("UserRoleManagementDialog", "Position", None))
        self.add_button.setText(_translate("UserRoleManagementDialog", "Add", None))
        self.update_button.setText(_translate("UserRoleManagementDialog", "Update", None))
        self.delete_button.setText(_translate("UserRoleManagementDialog", "Delete", None))
        self.label_8.setText(_translate("UserRoleManagementDialog", "Existing User Roles", None))
        self.label_15.setText(_translate("UserRoleManagementDialog", "Phone", None))
        self.groupBox_2.setTitle(_translate("UserRoleManagementDialog", "Groups", None))
        self.label_10.setText(_translate("UserRoleManagementDialog", "Groups Available", None))
        self.label_11.setText(_translate("UserRoleManagementDialog", "Groups the user is a member of", None))
        self.label_9.setText(_translate("UserRoleManagementDialog", "User Role Management", None))
        self.groupBox_3.setTitle(_translate("UserRoleManagementDialog", "Spatial Restrictions", None))
        self.label_12.setText(_translate("UserRoleManagementDialog", "Aimag / Duureg", None))
        self.label_13.setText(_translate("UserRoleManagementDialog", "Soum", None))
        self.label_14.setText(_translate("UserRoleManagementDialog", "Granted Aimags / Duuregs", None))
        self.label_16.setText(_translate("UserRoleManagementDialog", "Granted Soums", None))
        self.close_button.setText(_translate("UserRoleManagementDialog", "Close", None))

import resources_rc
